#!/usr/bin/env python3
"""Build Week 3-4 Rank 11 through Rank 15 article and Type 3 assets."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent))

from build_week34_rank9_10_batch import (  # noqa: E402
    ROOT,
    checklist,
    consolidated,
    load_csv,
    product,
    prompt_flatlay,
    prompt_people,
    raw_image,
    write_json,
)


def sec(h2: str, lines: list[str], key: str | None = None) -> dict[str, object]:
    return {"key": key or h2.lower().replace(" ", "_"), "h2": h2, "lines": lines}


def manifest_slot(
    *,
    item: dict[str, object],
    alt: str,
    caption: str,
    refs: list[str],
    roles: list[str],
    prompt: str,
) -> dict[str, object]:
    return {
        **item,
        "alt": alt,
        "caption": caption,
        "product": {"code": item["code"], "name": item["name"], "pdp": item["pdp"]},
        "local_reference_images": refs,
        "ref_roles": roles,
        "prompt": prompt,
    }


def write_article(
    *,
    rank: int,
    prefix: str,
    title: str,
    slug: str,
    meta_desc: str,
    focus_kw: str,
    intro: list[str],
    sections: list[dict[str, object]],
    faqs: list[tuple[str, str]],
    config: dict[str, object],
    optimize: bool,
    manifest: dict[str, object],
) -> None:
    assert 150 <= len(meta_desc) <= 160, (title, len(meta_desc))
    assert len(title) <= 60, (title, len(title))
    sections_json = f"output/{prefix}_sections.json"
    type3_json = f"output/{prefix}_type3_prompts.json"
    write_json(
        sections_json,
        {
            "meta": {
                "title": title,
                "slug": slug,
                "meta_desc": meta_desc,
                "focus_kw": focus_kw,
                "yoast_title": title,
            },
            "intro": intro,
            "sections": sections,
            "faqs": faqs,
        },
    )
    write_json(
        f"output/publish_configs/week34_rank{rank}.json",
        {
            "rank": f"Week3-4 Rank {rank}",
            "sections_json": sections_json,
            "output_prefix": prefix,
            "carousel_id": config["carousel_id"],
            "occasion_year": config["occasion_year"],
            "carousel_alt_prefix": config["carousel_alt_prefix"],
            "gift_h2": config["gift_h2"],
            "gift_blurb": config["gift_blurb"],
            "conclusion_html": config["conclusion_html"],
            "schema_keywords": config["schema_keywords"],
            "type3_prompts_json": type3_json,
            "products": config["products"],
            "flatlay_insert_h2": config["flatlay_insert_h2"],
            "lifestyle_insert_h2": config["lifestyle_insert_h2"],
            "more_reads_html": config["more_reads_html"],
            "how_to_html": config["how_to_html"],
            "faq_h2": config["faq_h2"],
            "min_lines": config.get("min_lines", 84),
        },
    )
    write_json(type3_json, manifest)
    checklist(prefix, rank, title, focus_kw, optimize)


def common_faqs(topic: str, short_use: str) -> list[tuple[str, str]]:
    return [
        (f"What should I write for {topic}?", f"Write a short, sincere line that matches the relationship and the channel. For {short_use}, keep it warm, clear, and easy to copy."),
        (f"Can I use these {topic} lines on WhatsApp?", "Yes. Pick a short line for status, a warmer line for a personal chat, and a longer note when you are sending it to a close friend or family member."),
        ("How do I make the message feel personal?", "Add a name, one shared memory, or a simple blessing. A tiny personal detail makes even a short message feel thoughtful."),
        ("Should I send a funny or emotional message?", "Use funny lines with close friends who enjoy teasing. Use emotional lines for cards, family groups, and people who prefer heartfelt notes."),
        ("Can I pair the message with a gift?", "Yes. A small jewellery keepsake works well when the message marks a special bond, festival, or family ritual."),
    ]


def manifest_base(rank: int, slug: str, focus_kw: str, prefix: str, caption_occasion: str, flatlay_setting: str, keywords: list[str]) -> dict[str, object]:
    return {
        "rank": f"Week3-4 Rank {rank}",
        "slug": slug,
        "primary_kw": focus_kw,
        "output_prefix": prefix,
        "caption_occasion": caption_occasion,
        "caption_year": "2026",
        "flatlay_setting": flatlay_setting,
        "workflow": "Higgsfield CLI nano_banana_pro. People shots require @img1 body_image plus @img2 design. Max 2 concurrent generations total. If queue/generation error occurs, wait 40-50 seconds before retry. No visible screens/devices.",
        "higgsfield_jobs": {},
        "higgsfield": {"model": "nano_banana_pro", "aspect_ratio": "16:9", "resolution": "2k", "count": 1},
        "insert_h2s_json": f"output/{prefix}_insert_h2s.json",
        "product_media_json": f"output/{prefix}_product_media.json",
        "output": {
            "hero": f"output/magnific_generated/{slug.replace('-2026','')}-hero-2026.webp",
            "flatlay": f"output/magnific_generated/{slug.replace('-2026','')}-flatlay-2026.webp",
            "lifestyle": f"output/magnific_generated/{slug.replace('-2026','')}-lifestyle-2026.webp",
        },
        "media_titles": {
            "hero": f"{focus_kw} 2026 Hero",
            "flatlay": f"{focus_kw} 2026 Flatlay",
            "lifestyle": f"{focus_kw} 2026 Lifestyle",
        },
        "schema_keywords": keywords,
        "slots": {},
    }


def build() -> None:
    product_rows = load_csv("docs/product/Seo Products - consolidated.csv")
    detail_rows = product_rows

    # Rank 11
    r11_prefix = "Week34_Rank11_FriendshipDayMsg"
    r11_slug = "happy-friendship-day-quotes-2026"
    r11_kw = "happy friendship day quotes"
    r11_keywords = ["friendship day msg", r11_kw, "friendship day wishes", "best friend quotes", "friendship captions"]
    r11_products = [
        product(product_rows, "The Tapia Chain Bracelet"),
        product(product_rows, "The Gigi Ring"),
        product(product_rows, "The Rohal Huggie Earrings"),
        product(product_rows, "The Pervinca Charm Holder Bracelet"),
        product(product_rows, "The Aagarna Pendant"),
        product(product_rows, "The Shining Star Bracelet"),
    ]
    r11_hero = consolidated(detail_rows, "The Shining Star Bracelet")
    r11_flat = consolidated(detail_rows, "The Quinn Ring")
    r11_life = consolidated(detail_rows, "The Faliha Purse Hoop Earrings")
    r11_manifest = manifest_base(11, r11_slug, r11_kw, r11_prefix, "Friendship Day", "window-tea-table", r11_keywords)
    r11_manifest["slots"] = {
        "hero": manifest_slot(
            item=r11_hero,
            alt="happy friendship day quotes 2026 hero with The Shining Star Bracelet",
            caption="Friendship Day 2026 mood: The Shining Star Bracelet",
            refs=[raw_image("Bracelets", "The Shining Star Bracelet", "1_body_portrait.png"), raw_image("Bracelets", "The Shining Star Bracelet", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Happy Friendship Day quotes 2026 hero",
                scene="solo fair-skinned Indian adult woman in a soft ivory kurta tying a small ribbon on a wrapped gift box beside flowers and two ceramic cups, full face visible, wrist and bracelet clearly visible, warm living room, affectionate best friend mood",
                product_name="The Shining Star Bracelet",
                product=r11_hero,
                body_part="wrist",
                extra_negatives="phone in hand, blank greeting card, friendship band, extra bracelet, watch",
            ),
        ),
        "flatlay": manifest_slot(
            item=r11_flat,
            alt="happy friendship day quotes 2026 flatlay with The Quinn Ring",
            caption="Friendship Day 2026 detail: The Quinn Ring",
            refs=[raw_image("Rings", "The Quinn Ring", "0_primary.png"), raw_image("Rings", "The Quinn Ring", "2_front.png"), raw_image("Rings", "The Quinn Ring", "6_angle.png")],
            roles=["primary", "front", "angle"],
            prompt=prompt_flatlay(
                occasion="Happy Friendship Day quotes 2026",
                setting="window-tea-table",
                setting_prompt="warm wooden tea table near a sunlit window with a small wrapped gift, loose ribbon, dried flowers, ceramic cup, closed blank book blurred at edge, no card and no text",
                product_name="The Quinn Ring",
                product=r11_flat,
            ),
        ),
        "lifestyle": manifest_slot(
            item=r11_life,
            alt="happy friendship day quotes 2026 lifestyle with The Faliha Purse Hoop Earrings",
            caption="Friendship Day 2026 look: The Faliha Purse Hoop Earrings",
            refs=[raw_image("Earrings", "The Faliha Purse Hoop Earrings", "1_body_portrait.png"), raw_image("Earrings", "The Faliha Purse Hoop Earrings", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Happy Friendship Day quotes 2026 lifestyle",
                scene="solo fair-skinned Indian adult woman smiling while arranging fresh flowers and a ribbon on a table, no device, no card facing camera, full head visible and both ears visible, simple cream blouse, no necklace and wrists out of frame",
                product_name="The Faliha Purse Hoop Earrings",
                product=r11_life,
                body_part="ear",
                extra_negatives="necklace, bracelet, ring, watch, greeting card, phone",
            ),
        ),
    }
    friendship_sections = [
        sec("Happy Friendship Day Quotes", [
            "Happy Friendship Day to the person who makes ordinary days feel lighter.",
            "A true friend turns small moments into lifelong memories.",
            "Happy Friendship Day, may our bond stay honest, funny, and strong.",
            "Some friendships feel like home, and yours is one of them.",
            "Thank you for being the calm voice, the loud laugh, and the loyal heart.",
            "Life feels brighter when a good friend walks beside you.",
            "Happy Friendship Day to my chosen family and forever teammate.",
            "A best friend is the blessing you can laugh with and lean on.",
            "May our friendship keep growing through every season.",
            "Good friends make the heavy days easier and the happy days fuller.",
            "Happy Friendship Day, thank you for showing up again and again.",
            "Here is to a friendship that feels real, rare, and deeply loved.",
        ]),
        sec("Friendship Day Msg for Best Friend", [
            "You are the person I can call without rehearsing a single word.",
            "Happy Friendship Day, bestie. Thank you for knowing my silence too.",
            "Our friendship is full of jokes, advice, memories, and perfect timing.",
            "You make life feel less complicated and much more fun.",
            "Best friends are rare, and I am lucky mine is you.",
            "Thank you for being my safe place and my loudest cheerleader.",
            "Happy Friendship Day to the one who has seen every version of me.",
            "You make ordinary chats feel like therapy and celebration together.",
            "No distance can reduce what a real best friend means.",
            "I hope our friendship keeps collecting stories for years.",
            "You are not just my friend, you are my favourite constant.",
            "Happy Friendship Day, keep being your wonderfully chaotic self.",
        ]),
        sec("Short Friendship Day Wishes", [
            "Happy Friendship Day, my favourite human.",
            "Grateful for you today and always.",
            "Best friends make life glow.",
            "Cheers to us and our memories.",
            "Your friendship is a blessing.",
            "Forever thankful for your heart.",
            "Happy Friendship Day, stay close.",
            "Friends like you are rare.",
            "Sending love, laughter, and gratitude.",
            "You make life kinder.",
            "Our bond is my comfort.",
            "Happy Friendship Day, bestie.",
        ]),
        sec("Funny Friendship Day Messages", [
            "Happy Friendship Day to the person who knows too much and still stays.",
            "You are proof that chaos can be lovable.",
            "Thanks for laughing at my jokes, even the emergency backup ones.",
            "Our friendship survives bad plans, late replies, and dramatic stories.",
            "Happy Friendship Day to my unpaid therapist and snack partner.",
            "You are weird, I am weird, and somehow this works beautifully.",
            "A good friend supports you. A best friend judges your choices with snacks.",
            "Thank you for being the reason my serious face never lasts.",
            "Life gave me a friend, then gave that friend excellent gossip stamina.",
            "Happy Friendship Day, please continue tolerating my nonsense.",
            "Our friendship deserves an award for emotional damage control.",
            "You are my favourite bad influence with a good heart.",
        ]),
        sec("Emotional Friendship Day Quotes", [
            "Some people arrive quietly and become impossible to imagine life without.",
            "A true friendship is felt most on days when words are few.",
            "You have stood beside me in ways I will never forget.",
            "Happy Friendship Day to the friend who made difficult chapters softer.",
            "The best friendships are not loud all the time, but they are always present.",
            "Your kindness has been a steady light in my life.",
            "Thank you for understanding what I cannot always explain.",
            "A real friend carries your joy gently and your pain with care.",
            "Happy Friendship Day, I am grateful for the comfort of your presence.",
            "Some bonds are not measured by time, but by trust.",
            "You have made many days easier just by being there.",
            "May this friendship remain one of my life’s quiet treasures.",
        ]),
        sec("Friendship Day Captions", [
            "Good friends, warm memories, full heart.",
            "Friendship Day with my favourite constant.",
            "Built on laughter, loyalty, and too many stories.",
            "Best friend energy, always.",
            "A little chaos, a lot of love.",
            "Celebrating the bond that keeps me grounded.",
            "Friends who feel like sunshine.",
            "Real ones, rare ones, forever ones.",
            "Our kind of friendship is priceless.",
            "Happy Friendship Day from us to the memory book.",
            "Grateful for this bond and every laugh in it.",
            "Friendship looks good on us.",
        ]),
        sec("Friendship Day Gift Message Ideas", [
            "Add one honest line before giving the gift so it feels personal.",
            "Choose a keepsake when your message is about lasting friendship.",
            "A bracelet works well for friends who love daily reminders.",
            "A ring can mark a promise, a shared milestone, or a special memory.",
            "Small earrings make a thoughtful gift for a friend who likes subtle style.",
            "Keep the note short when the gift already carries emotion.",
            "Mention one memory that makes your friendship special.",
            "Avoid generic lines if you are gifting something meaningful.",
            "A simple thank you can be more powerful than a long speech.",
            "Pick warm wrapping, fresh flowers, and a handwritten name tag turned inward.",
            "Let the jewellery support the message, not replace it.",
            "The best gift feels chosen, not rushed.",
        ]),
    ]
    write_article(
        rank=11,
        prefix=r11_prefix,
        title="Happy Friendship Day Quotes 2026",
        slug=r11_slug,
        meta_desc="Happy Friendship Day quotes 2026 with friendship day msg ideas, wishes, captions, short lines, emotional notes, funny messages, and best friend greetings.",
        focus_kw=r11_kw,
        intro=[
            "Looking for friendship day msg ideas that feel warm, real, and easy to send? This 2026 collection brings together happy friendship day quotes, short wishes, funny lines, emotional notes, captions, and gift message ideas for the friends who make life feel lighter.",
            "TL;DR: Use a short wish for WhatsApp, an emotional quote for a close friend, a funny line for your bestie, and a personal gift note when you want the message to feel remembered.",
        ],
        sections=friendship_sections,
        faqs=common_faqs("Friendship Day", "friendship day msg ideas"),
        config={
            "carousel_id": "bs-cf-friendshipdaymsg",
            "occasion_year": "Friendship Day 2026",
            "carousel_alt_prefix": "happy friendship day quotes 2026 gift idea",
            "gift_h2": "Friendship Day Gift Ideas for Close Friends",
            "gift_blurb": "A friendship message feels even sweeter when it comes with a small keepsake. These BlueStone picks are easy to pair with a note, a memory, or a simple promise to stay close.",
            "conclusion_html": "The best happy friendship day quotes sound like your real bond. Pick a line that matches your friend, add one personal detail, and send it with warmth instead of overthinking.",
            "schema_keywords": r11_keywords,
            "products": r11_products,
            "flatlay_insert_h2": "Friendship Day Msg for Best Friend",
            "lifestyle_insert_h2": "Friendship Day Gift Message Ideas",
            "more_reads_html": 'Read more ideas in <a href="https://blog.bluestone.com/international-friendship-day-quotes-2026/">international friendship quotes</a>, <a href="https://blog.bluestone.com/best-friend-shayari-2026/">best friend shayari</a>, and <a href="https://blog.bluestone.com/friendship-day-gifts-2026/">friendship gifts</a>.',
            "how_to_html": "Match the line to the friend. Use humour for the friend who loves teasing, a heartfelt quote for someone who has supported you, and a short caption when you are posting a photo together.",
            "faq_h2": "Frequently Asked Questions about Friendship Day Messages",
            "min_lines": 84,
        },
        optimize=False,
        manifest=r11_manifest,
    )

    # Rank 12
    r12_prefix = "Week34_Rank12_DevDiwaliWishes"
    r12_slug = "happy-dev-diwali-wishes-in-english-2026"
    r12_kw = "happy dev diwali wishes in english"
    r12_keywords = [r12_kw, "dev diwali wishes", "dev diwali messages", "dev diwali captions", "dev deepawali greetings"]
    r12_products = [
        product(product_rows, "The Xarvithis Pendant"),
        product(product_rows, "The Channing Bangle"),
        product(product_rows, "The Ursa Hoop Earrings"),
        product(product_rows, "The Muricelle Bangle"),
        product(product_rows, "The Pear Evil Eye Toggle Bangle"),
        product(product_rows, "The Aagarna Pendant"),
    ]
    r12_hero = consolidated(detail_rows, "The Xarvithis Pendant")
    r12_flat = consolidated(detail_rows, "The Channing Bangle")
    r12_life = consolidated(detail_rows, "The Ursa Hoop Earrings")
    r12_manifest = manifest_base(12, r12_slug, r12_kw, r12_prefix, "Dev Diwali", "brass-diya-thali", r12_keywords)
    r12_manifest["slots"] = {
        "hero": manifest_slot(
            item=r12_hero,
            alt="happy dev diwali wishes in English 2026 hero with The Xarvithis Pendant",
            caption="Dev Diwali 2026 mood: The Xarvithis Pendant",
            refs=[raw_image("Pendants", "The Xarvithis Pendant", "1_body_portrait.png"), raw_image("Pendants", "The Xarvithis Pendant", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Happy Dev Diwali wishes in English 2026 hero",
                scene="solo fair-skinned Indian adult woman in an ivory silk kurta placing a brass diya on a low festive tray with marigold flowers and a small wrapped gift, full face visible, neck and pendant clearly visible, peaceful evening home temple corner",
                product_name="The Xarvithis Pendant",
                product=r12_hero,
                body_part="neck",
                extra_negatives="large pendant, extra necklace, temple text, framed readable text",
            ),
        ),
        "flatlay": manifest_slot(
            item=r12_flat,
            alt="happy dev diwali wishes in English 2026 flatlay with The Channing Bangle",
            caption="Dev Diwali 2026 detail: The Channing Bangle",
            refs=[raw_image("Bangles", "The Channing Bangle", "0_primary.png"), raw_image("Bangles", "The Channing Bangle", "2_front.png"), raw_image("Bangles", "The Channing Bangle", "4_close_up.png")],
            roles=["primary", "front", "close_up"],
            prompt=prompt_flatlay(
                occasion="Happy Dev Diwali wishes in English 2026",
                setting="brass-diya-thali",
                setting_prompt="cream silk fabric with a brass thali, unmarked diya, marigold petals, folded ribbon, tiny wrapped gift box, soft candle glow, no paper and no text",
                product_name="The Channing Bangle",
                product=r12_flat,
            ),
        ),
        "lifestyle": manifest_slot(
            item=r12_life,
            alt="happy dev diwali wishes in English 2026 lifestyle with The Ursa Hoop Earrings",
            caption="Dev Diwali 2026 look: The Ursa Hoop Earrings",
            refs=[raw_image("Earrings", "The Ursa Hoop Earrings", "1_body_portrait.png"), raw_image("Earrings", "The Ursa Hoop Earrings", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Happy Dev Diwali wishes in English 2026 lifestyle",
                scene="solo fair-skinned Indian adult woman lighting a diya near flowers and a brass bowl, full head visible and both ears visible, cream festive blouse, no necklace and wrists out of frame, serene devotional festive mood",
                product_name="The Ursa Hoop Earrings",
                product=r12_life,
                body_part="ear",
                extra_negatives="necklace, bracelet, ring, watch, phone, poster, religious text",
            ),
        ),
    }
    dev_sections = [
        sec("Happy Dev Diwali Wishes in English", [
            "Happy Dev Diwali. May divine light fill your home with peace, wisdom, and blessings.",
            "Wishing you a Dev Diwali full of faith, joy, and beautiful new beginnings.",
            "May the lamps of Dev Diwali remove darkness from every corner of your life.",
            "Happy Dev Diwali. May your heart stay calm, grateful, and guided by light.",
            "On this sacred festival, may your family receive happiness and protection.",
            "May Dev Diwali bring spiritual brightness and gentle abundance to your home.",
            "Wishing you a peaceful Dev Diwali blessed with hope and harmony.",
            "May every diya you light carry a prayer of love and prosperity.",
            "Happy Dev Diwali to you and your family. Stay blessed and joyful.",
            "May this Dev Diwali awaken kindness, courage, and devotion within you.",
            "Sending warm wishes for a bright, calm, and blessed Dev Diwali.",
            "May divine grace make this festival meaningful for every heart in your home.",
        ]),
        sec("Short Dev Diwali Wishes", [
            "Happy Dev Diwali to you.",
            "May divine light bless you.",
            "Wishing you peace and joy.",
            "May every diya bring hope.",
            "Blessed Dev Diwali wishes.",
            "Light, faith, and happiness to you.",
            "May your home glow with grace.",
            "Peaceful Dev Diwali greetings.",
            "May blessings brighten your path.",
            "Joyful Dev Diwali to your family.",
            "May devotion guide your heart.",
            "Warm wishes for Dev Diwali.",
        ]),
        sec("Dev Diwali Messages for Family", [
            "Happy Dev Diwali to my family. May our home stay filled with peace and shared prayers.",
            "May this sacred evening bring love, patience, and blessings to everyone at home.",
            "Wishing our family a Dev Diwali full of diyas, gratitude, and togetherness.",
            "May divine light protect our home and guide every step we take.",
            "Happy Dev Diwali. I am grateful for family, faith, and the comfort of being together.",
            "May our home glow with kindness and our hearts remain united.",
            "Sending prayers for health, happiness, and prosperity for all of us.",
            "May this Dev Diwali make every family bond warmer and stronger.",
            "Let us celebrate with simple prayers, bright lamps, and grateful hearts.",
            "May the blessings of this festival stay with our family all year.",
            "Happy Dev Diwali to the people who make every festival meaningful.",
            "May light, devotion, and love guide our home today.",
        ]),
        sec("Dev Diwali Captions", [
            "Diyas, devotion, and a peaceful heart.",
            "Dev Diwali glow and grateful prayers.",
            "Light that feels sacred.",
            "A calm evening wrapped in divine brightness.",
            "Faith looks beautiful in lamp light.",
            "Blessed moments, golden glow.",
            "Dev Diwali mood: peaceful and thankful.",
            "Let every diya carry a prayer.",
            "Sacred lights, softer hearts.",
            "Celebrating faith with warmth and grace.",
            "A festival of devotion and light.",
            "Tonight, every glow feels like a blessing.",
        ]),
        sec("Dev Diwali Quotes", [
            "The light we offer outside should awaken kindness within.",
            "A diya becomes sacred when it is lit with gratitude.",
            "Dev Diwali reminds us that faith can make ordinary light feel divine.",
            "Where devotion lives, every corner becomes brighter.",
            "Peace is the most beautiful blessing of a sacred festival.",
            "Light is not only seen, it is felt in a calm heart.",
            "A prayer said with sincerity glows longer than a lamp.",
            "Dev Diwali is a reminder to choose hope over fear.",
            "The brightest celebration begins with a grateful soul.",
            "When faith and light meet, the evening becomes holy.",
            "A quiet diya can carry the deepest prayer.",
            "Let the festival light your path with wisdom.",
        ]),
        sec("Dev Diwali WhatsApp Status", [
            "Happy Dev Diwali. May divine light guide us all.",
            "A sacred evening, a peaceful prayer, and a glowing heart.",
            "May every diya brighten your destiny.",
            "Celebrating Dev Diwali with faith and gratitude.",
            "Light the lamp, offer thanks, and welcome blessings.",
            "May this Dev Diwali bring calm to every home.",
            "Blessed by light, guided by devotion.",
            "Dev Diwali vibes: serene, golden, and grateful.",
            "May your heart shine with divine peace.",
            "A festival where every flame feels like hope.",
            "Sending bright Dev Diwali wishes to everyone.",
            "May blessings flow like light tonight.",
        ]),
        sec("Dev Diwali Gift Message Ideas", [
            "Pair a short blessing with a simple jewellery keepsake.",
            "Choose a pendant when the message is about light close to the heart.",
            "A bangle feels festive for someone who loves traditional details.",
            "Earrings are a graceful choice for a subtle devotional celebration.",
            "Write one prayer and one personal wish on the note.",
            "Keep the gift message calm, sincere, and easy to remember.",
            "Use warm wrapping, flowers, and a diya rather than printed props.",
            "Avoid overloading the message with too many blessings.",
            "A thoughtful keepsake can make a simple wish feel special.",
            "Let the jewellery be an extension of the festival glow.",
            "Choose designs that feel elegant, not loud.",
            "The best Dev Diwali gift feels peaceful and personal.",
        ]),
    ]
    write_article(
        rank=12,
        prefix=r12_prefix,
        title="Happy Dev Diwali Wishes in English 2026",
        slug=r12_slug,
        meta_desc="Happy Dev Diwali wishes in English 2026 with short greetings, messages, captions, quotes, prayers, and warm lines for family, friends, and groups today.",
        focus_kw=r12_kw,
        intro=[
            "Happy Dev Diwali wishes in English should feel devotional, calm, and easy to share. Use these 2026 wishes for family chats, WhatsApp status, captions, cards, and festive messages that honour the sacred glow of Dev Diwali.",
            "TL;DR: Send a short blessing for WhatsApp, a devotional wish for family, a peaceful quote for captions, and a personal gift message when you are pairing the greeting with a keepsake.",
        ],
        sections=dev_sections,
        faqs=common_faqs("Dev Diwali", "happy dev diwali wishes in English"),
        config={
            "carousel_id": "bs-cf-devdiwaliwishes",
            "occasion_year": "Dev Diwali 2026",
            "carousel_alt_prefix": "happy dev diwali wishes in English 2026 gift idea",
            "gift_h2": "Dev Diwali Gift Ideas with Blessing Notes",
            "gift_blurb": "Dev Diwali gifting works best when it feels calm, devotional, and thoughtful. These BlueStone pieces pair well with a blessing, a prayer, or a warm family note.",
            "conclusion_html": "Happy Dev Diwali wishes in English work best when they carry light, faith, and calm affection. Choose the wish that suits your recipient, then add one sincere blessing.",
            "schema_keywords": r12_keywords,
            "products": r12_products,
            "flatlay_insert_h2": "Dev Diwali Messages for Family",
            "lifestyle_insert_h2": "Dev Diwali Gift Message Ideas",
            "more_reads_html": 'Read more festive ideas in <a href="https://blog.bluestone.com/diwali-wishes-and-quotes-2026/">Diwali wishes and quotes</a>, <a href="https://blog.bluestone.com/advance-happy-diwali-2026/">advance Happy Diwali wishes</a>, and <a href="https://blog.bluestone.com/slogan-on-diwali-2026/">Diwali slogans</a>.',
            "how_to_html": "Choose a devotional wish for elders, a short greeting for WhatsApp, and a peaceful quote for captions. If you are sending a gift, add one blessing that sounds personal.",
            "faq_h2": "Frequently Asked Questions about Dev Diwali Wishes",
            "min_lines": 84,
        },
        optimize=True,
        manifest=r12_manifest,
    )

    # Rank 13
    r13_prefix = "Week34_Rank13_DiwaliWhatsapp"
    r13_slug = "diwali-whatsapp-2026"
    r13_kw = "diwali whatsapp"
    r13_keywords = [r13_kw, "diwali whatsapp status", "diwali whatsapp messages", "diwali wishes", "diwali captions"]
    r13_products = [
        product(product_rows, "The Aagarna Pendant"),
        product(product_rows, "The Ebony Ring"),
        product(product_rows, "The Skein Hoop Earrings"),
        product(product_rows, "The Shining Star Bracelet"),
        product(product_rows, "The Quinn Ring"),
        product(product_rows, "The Ursa Hoop Earrings"),
    ]
    r13_hero = consolidated(detail_rows, "The Aagarna Pendant")
    r13_flat = consolidated(detail_rows, "The Ebony Ring")
    r13_life = consolidated(detail_rows, "The Skein Hoop Earrings")
    r13_manifest = manifest_base(13, r13_slug, r13_kw, r13_prefix, "Diwali WhatsApp", "rangoli-gift-tray", r13_keywords)
    r13_manifest["slots"] = {
        "hero": manifest_slot(
            item=r13_hero,
            alt="diwali whatsapp 2026 hero with The Aagarna Pendant",
            caption="Diwali WhatsApp 2026 mood: The Aagarna Pendant",
            refs=[raw_image("Pendants", "The Aagarna Pendant", "1_body_portrait.png"), raw_image("Pendants", "The Aagarna Pendant", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Diwali WhatsApp 2026 hero",
                scene="solo fair-skinned Indian adult woman in a cream festive kurta arranging marigold flowers and a small wrapped gift box on a table, no phone, full face visible, neck and pendant clearly visible, warm home celebration mood",
                product_name="The Aagarna Pendant",
                product=r13_hero,
                body_part="neck",
                extra_negatives="large pendant, extra necklace, phone, laptop, blank message card",
            ),
        ),
        "flatlay": manifest_slot(
            item=r13_flat,
            alt="diwali whatsapp 2026 flatlay with The Ebony Ring",
            caption="Diwali WhatsApp 2026 detail: The Ebony Ring",
            refs=[raw_image("Rings", "The Ebony Ring", "0_primary.png"), raw_image("Rings", "The Ebony Ring", "2_front.png"), raw_image("Rings", "The Ebony Ring", "6_angle.png")],
            roles=["primary", "front", "angle"],
            prompt=prompt_flatlay(
                occasion="Diwali WhatsApp 2026",
                setting="rangoli-gift-tray",
                setting_prompt="top-down cream tray with marigold petals, brass diya, silk ribbon, tiny wrapped gift, blurred rangoli colours at corners, no paper and no text",
                product_name="The Ebony Ring",
                product=r13_flat,
            ),
        ),
        "lifestyle": manifest_slot(
            item=r13_life,
            alt="diwali whatsapp 2026 lifestyle with The Skein Hoop Earrings",
            caption="Diwali WhatsApp 2026 look: The Skein Hoop Earrings",
            refs=[raw_image("Earrings", "The Skein Hoop Earrings", "1_body_portrait.png"), raw_image("Earrings", "The Skein Hoop Earrings", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Diwali WhatsApp 2026 lifestyle",
                scene="solo fair-skinned Indian adult woman laughing while placing sweets into a brass bowl beside flowers and diyas, no device, full head visible and both ears visible, soft ivory blouse, no necklace and wrists out of frame",
                product_name="The Skein Hoop Earrings",
                product=r13_life,
                body_part="ear",
                extra_negatives="necklace, bracelet, ring, watch, phone, blank screen, text card",
            ),
        ),
    }
    whatsapp_sections = [
        sec("Diwali WhatsApp Messages", [
            "Wishing you a Diwali filled with light, laughter, peace, and beautiful new beginnings.",
            "May every diya brighten your home and every smile brighten your heart.",
            "Happy Diwali. May this festival bring prosperity, health, and togetherness.",
            "Sending warm Diwali wishes to you and your loved ones.",
            "May your home glow with happiness and your heart glow with gratitude.",
            "Happy Diwali. Let light, love, and kindness guide the year ahead.",
            "Wishing you sweets, sparkle, and peaceful festive memories.",
            "May this Diwali remove worries and welcome hope.",
            "Happy Diwali to your family. Stay blessed, joyful, and safe.",
            "May the festival of lights bring abundance into every corner of your life.",
            "Sending love and festive blessings through this message.",
            "May your Diwali be simple, bright, and full of warmth.",
        ]),
        sec("Diwali WhatsApp Status", [
            "Diyas lit, heart grateful.",
            "Diwali glow and family warmth.",
            "Light, love, sweets, and smiles.",
            "May every corner shine with hope.",
            "Festive mood: golden and grateful.",
            "Happy Diwali from my home to yours.",
            "A little sparkle, a lot of peace.",
            "Let kindness glow brighter than lights.",
            "Diwali feels like home.",
            "Blessings, brightness, and beautiful beginnings.",
            "Tonight belongs to light.",
            "Celebrating the joy of Diwali.",
        ]),
        sec("Short Diwali WhatsApp Wishes", [
            "Happy Diwali to you.",
            "May light bless your home.",
            "Wishing you joy and peace.",
            "Stay blessed this Diwali.",
            "Warm Diwali wishes.",
            "May happiness glow within.",
            "Sending festive love.",
            "Have a bright Diwali.",
            "May prosperity visit your home.",
            "Celebrate safely and happily.",
            "Joyful Diwali greetings.",
            "Light and love to all.",
        ]),
        sec("Diwali WhatsApp Captions", [
            "Golden lights and grateful nights.",
            "Festival glow, family love.",
            "Diyas, sweets, and a full heart.",
            "My Diwali mood is warm and bright.",
            "Where there is light, there is hope.",
            "Keeping Diwali simple and beautiful.",
            "Festive sparkle with peaceful energy.",
            "A home lit with love.",
            "This Diwali feels soft, golden, and happy.",
            "Every diya tells a story of hope.",
            "Celebrating light in small moments.",
            "Diwali memories in the making.",
        ]),
        sec("Diwali WhatsApp Group Messages", [
            "Wishing everyone in this group a joyful and peaceful Diwali.",
            "May your families be blessed with health, harmony, and happiness.",
            "Happy Diwali to all. May this festival bring light into every home.",
            "Sending festive greetings to everyone here with warm wishes.",
            "May the year ahead be bright, kind, and prosperous for all of us.",
            "Let us celebrate Diwali with safety, love, and gratitude.",
            "Wishing this group laughter, sweets, and wonderful memories.",
            "May every diya bring a reason to smile.",
            "Happy Diwali. Stay blessed and enjoy the celebrations.",
            "May your homes shine with peace and positivity.",
            "Sending good wishes to every family represented here.",
            "Have a safe, bright, and meaningful Diwali.",
        ]),
        sec("Diwali WhatsApp Messages for Family", [
            "Happy Diwali to my family. May our home stay bright with love and peace.",
            "Grateful for the warmth of family on this beautiful festival.",
            "May our bond grow stronger with every diya we light together.",
            "Wishing my family health, happiness, and endless blessings.",
            "Happy Diwali. Thank you for making every festival feel like home.",
            "May our celebrations stay full of laughter and kindness.",
            "Sending love to everyone at home this Diwali.",
            "May this festival bring harmony to every heart in our family.",
            "Diwali is brighter because we celebrate it together.",
            "May prosperity and peace stay with our family always.",
            "Happy Diwali to the people I love most.",
            "Let this festival remind us to cherish each other.",
        ]),
        sec("Diwali Gift Message Ideas", [
            "Pair a short WhatsApp wish with a small gift when you want the gesture to last.",
            "Choose a pendant for someone who loves subtle festive elegance.",
            "A ring can make a simple wish feel more memorable.",
            "Earrings are an easy pick for friends and sisters who like everyday sparkle.",
            "Keep the note short enough to send and warm enough to save.",
            "Avoid screen props in gift photos and use flowers or diyas instead.",
            "Mention the reason you chose the piece.",
            "A line about light and love works well with jewellery.",
            "Let the message feel personal, not copied.",
            "Simple wrapping and a sincere note can make the gift feel premium.",
            "Choose pieces that match the recipients everyday style.",
            "A thoughtful Diwali keepsake can outlast the festive rush.",
        ]),
    ]
    write_article(
        rank=13,
        prefix=r13_prefix,
        title="Diwali WhatsApp 2026",
        slug=r13_slug,
        meta_desc="Diwali WhatsApp 2026 messages, status lines, captions, greetings, short wishes, group messages, and festive lines to share with family and friends today.",
        focus_kw=r13_kw,
        intro=[
            "Diwali WhatsApp messages need to be quick to send but warm enough to feel personal. This 2026 collection has status lines, short wishes, captions, group messages, family greetings, and gift note ideas for the festival of lights.",
            "TL;DR: Use short wishes for chats, status lines for updates, captions for festive photos, and family messages when you want the greeting to feel closer.",
        ],
        sections=whatsapp_sections,
        faqs=common_faqs("Diwali WhatsApp", "Diwali WhatsApp messages"),
        config={
            "carousel_id": "bs-cf-diwaliwhatsapp",
            "occasion_year": "Diwali 2026",
            "carousel_alt_prefix": "diwali whatsapp 2026 gift idea",
            "gift_h2": "Diwali Gift Ideas for WhatsApp Wishes",
            "gift_blurb": "If a Diwali WhatsApp wish is for someone close, a small keepsake can turn the message into a memory. These BlueStone pieces pair naturally with warm festive notes.",
            "conclusion_html": "The best Diwali WhatsApp message is short, warm, and easy to understand. Pick one that matches your recipient, then add a blessing or memory to make it yours.",
            "schema_keywords": r13_keywords,
            "products": r13_products,
            "flatlay_insert_h2": "Diwali WhatsApp Captions",
            "lifestyle_insert_h2": "Diwali Gift Message Ideas",
            "more_reads_html": 'Read more festive ideas in <a href="https://blog.bluestone.com/diwali-wishes-and-quotes-2026/">Diwali wishes and quotes</a>, <a href="https://blog.bluestone.com/diwali-quotes-for-instagram-2026/">Diwali Instagram captions</a>, and <a href="https://blog.bluestone.com/happy-diwali-poster-2026/">Diwali poster ideas</a>.',
            "how_to_html": "For WhatsApp, keep the line short and friendly. Personal chats can carry one memory, group wishes should stay inclusive, and captions can be more poetic.",
            "faq_h2": "Frequently Asked Questions about Diwali WhatsApp Messages",
            "min_lines": 84,
        },
        optimize=False,
        manifest=r13_manifest,
    )

    # Rank 14
    r14_prefix = "Week34_Rank14_RakhiGreetingCard"
    r14_slug = "rakhi-greeting-card-2026"
    r14_kw = "rakhi greeting card"
    r14_keywords = [r14_kw, "rakhi card message", "raksha bandhan card", "rakhi wishes", "rakhi greeting"]
    r14_products = [
        product(product_rows, "The Protector Evil Eye Rakhi"),
        product(product_rows, "The Lumeelle Cluster Pendant"),
        product(product_rows, "The Vicky Hoop Earrings"),
        product(product_rows, "The Tapia Chain Bracelet"),
        product(product_rows, "The Gigi Ring"),
        product(product_rows, "The Pervinca Charm Holder Bracelet"),
    ]
    r14_hero = consolidated(detail_rows, "The Lumeelle Cluster Pendant")
    r14_flat = consolidated(detail_rows, "The Protector Evil Eye Rakhi")
    r14_life = consolidated(detail_rows, "The Vicky Hoop Earrings")
    r14_manifest = manifest_base(14, r14_slug, r14_kw, r14_prefix, "Rakhi greeting card", "rakhi-thali", r14_keywords)
    r14_manifest["slots"] = {
        "hero": manifest_slot(
            item=r14_hero,
            alt="rakhi greeting card 2026 hero with The Lumeelle Cluster Pendant",
            caption="Rakhi 2026 mood: The Lumeelle Cluster Pendant",
            refs=[raw_image("Pendants", "The Lumeelle Cluster Pendant", "1_body_portrait.png"), raw_image("Pendants", "The Lumeelle Cluster Pendant", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Rakhi greeting card 2026 hero",
                scene="solo fair-skinned Indian adult woman in a soft cream festive kurta preparing a rakhi thali with flowers, kumkum bowl, rice grains, and a small wrapped gift, no card facing camera, full face visible, neck and pendant clearly visible",
                product_name="The Lumeelle Cluster Pendant",
                product=r14_hero,
                body_part="neck",
                extra_negatives="large pendant, extra necklace, readable card, brother in frame, rakhi on wrist",
            ),
        ),
        "flatlay": manifest_slot(
            item=r14_flat,
            alt="rakhi greeting card 2026 flatlay with The Protector Evil Eye Rakhi",
            caption="Rakhi 2026 detail: The Protector Evil Eye Rakhi",
            refs=[raw_image("Adjustable Bracelets", "The Protector Evil Eye Rakhi", "0_primary.png"), raw_image("Adjustable Bracelets", "The Protector Evil Eye Rakhi", "2_side_1.png"), raw_image("Adjustable Bracelets", "The Protector Evil Eye Rakhi", "4_close_up.png")],
            roles=["primary", "side", "close_up"],
            prompt=prompt_flatlay(
                occasion="Rakhi greeting card 2026",
                setting="rakhi-thali",
                setting_prompt="cream festive surface with brass thali, roli bowl, rice grains, marigold flowers, folded fabric, small wrapped gift, no paper and no text",
                product_name="The Protector Evil Eye Rakhi",
                product=r14_flat,
            ),
        ),
        "lifestyle": manifest_slot(
            item=r14_life,
            alt="rakhi greeting card 2026 lifestyle with The Vicky Hoop Earrings",
            caption="Rakhi 2026 look: The Vicky Hoop Earrings",
            refs=[raw_image("Earrings", "The Vicky Hoop Earrings", "1_body_portrait.png"), raw_image("Earrings", "The Vicky Hoop Earrings", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="Rakhi greeting card 2026 lifestyle",
                scene="solo fair-skinned Indian adult woman smiling beside a rakhi thali and wrapped gift, hands arranging flowers not jewellery, full head visible and both ears visible, cream blouse, no necklace and wrists out of frame",
                product_name="The Vicky Hoop Earrings",
                product=r14_life,
                body_part="ear",
                extra_negatives="necklace, bracelet, ring, watch, readable greeting card, phone, brother in frame",
            ),
        ),
    }
    rakhi_sections = [
        sec("Rakhi Greeting Card Messages", [
            "Happy Rakhi. You have been my protector, my partner in crime, and my forever support.",
            "This rakhi greeting card carries love, gratitude, and every childhood memory we still laugh about.",
            "Dear brother, may this Raksha Bandhan bring you happiness, health, and success.",
            "Dear sister, your love makes every festival warmer and every home brighter.",
            "Happy Rakhi to the sibling who makes life louder, funnier, and safer.",
            "May our bond stay strong through distance, time, and every silly fight.",
            "This card is a small reminder that you are deeply loved.",
            "Happy Raksha Bandhan. Thank you for being my first friend and forever family.",
            "May this rakhi bring blessings, protection, and sweet memories.",
            "Our bond is made of teasing, care, secrets, and unconditional love.",
            "Sending you a rakhi greeting full of prayers and affection.",
            "Happy Rakhi. You are one of my life’s most precious blessings.",
        ]),
        sec("Short Rakhi Card Wishes", [
            "Happy Rakhi, stay blessed.",
            "Love you always, dear sibling.",
            "Our bond is forever.",
            "Wishing you joy and success.",
            "You are my lifelong support.",
            "Happy Raksha Bandhan.",
            "Blessings and love to you.",
            "Forever grateful for you.",
            "Rakhi love from my heart.",
            "Stay happy, stay protected.",
            "You make family beautiful.",
            "Sending warm Rakhi wishes.",
        ]),
        sec("Rakhi Greeting Card for Brother", [
            "Dear brother, thank you for protecting me in ways big and small.",
            "Happy Rakhi to the brother who has always been my strongest support.",
            "You tease me endlessly, but you also stand by me without question.",
            "May your life be filled with success, laughter, and peace.",
            "This rakhi greeting card is a small thank you for every caring moment.",
            "I am lucky to have a brother who feels like a shield and a friend.",
            "Happy Raksha Bandhan. May your dreams keep growing brighter.",
            "Thank you for being my emergency contact for everything in life.",
            "Our fights are temporary, but our bond is forever.",
            "May this Rakhi bring you blessings and new achievements.",
            "You make being a sister feel safe and special.",
            "Happy Rakhi, my dear brother. Keep smiling always.",
        ]),
        sec("Rakhi Greeting Card for Sister", [
            "Dear sister, you make every family moment softer and brighter.",
            "Happy Rakhi to the sister who turns care into an everyday habit.",
            "Thank you for your love, advice, laughter, and patience.",
            "May your life be filled with happiness, confidence, and beautiful surprises.",
            "This card carries all the love I do not say often enough.",
            "A sister is a friend, guide, memory keeper, and blessing together.",
            "Happy Raksha Bandhan. May you always feel loved and protected.",
            "Your presence makes every festival feel complete.",
            "Thank you for being my secret keeper and honest critic.",
            "May your smile stay bright through every season.",
            "Our bond is a gift I cherish deeply.",
            "Happy Rakhi, dear sister. You are precious to me.",
        ]),
        sec("Funny Rakhi Card Lines", [
            "Happy Rakhi to my sibling and full-time drama partner.",
            "You are annoying, but unfortunately irreplaceable.",
            "Thanks for stealing my snacks and still being lovable.",
            "Our fights deserve a trophy and our bond deserves a hug.",
            "Happy Rakhi. I promise to be nice for at least today.",
            "You are my emergency support and my daily headache.",
            "No one irritates me with this much emotional value.",
            "Rakhi reminder: I am still your favourite sibling.",
            "Thanks for keeping my secrets and exposing my snacks.",
            "We fight like rivals and care like best friends.",
            "Happy Raksha Bandhan. Gift expectations remain high.",
            "Sibling love is teasing with a lifetime warranty.",
        ]),
        sec("Rakhi Card Quotes", [
            "A rakhi is a thread, but the bond it celebrates is lifelong.",
            "Siblings are the people who know your past and still cheer for your future.",
            "Raksha Bandhan is a promise wrapped in love.",
            "The strongest bonds are made of care, memory, and forgiveness.",
            "A sibling is childhood that never fully leaves your side.",
            "Rakhi reminds us that protection can be emotional too.",
            "Love between siblings grows through every argument and apology.",
            "A simple thread can carry countless memories.",
            "Family love shines brightest in small rituals.",
            "A rakhi greeting card is a keepsake of affection.",
            "Siblings are proof that love can survive endless teasing.",
            "The bond of Rakhi is precious because it feels like home.",
        ]),
        sec("Rakhi Gift Message Ideas", [
            "Write one line about protection and one line about gratitude.",
            "Pair the card with a rakhi when you want the ritual to feel complete.",
            "Choose a pendant for a sister who likes classic keepsakes.",
            "Choose earrings for a sibling who enjoys everyday festive style.",
            "A bracelet or rakhi piece works well for brothers who love meaningful symbols.",
            "Keep the card free of long speeches if the gift is emotional.",
            "Mention a childhood memory to make the message personal.",
            "Use flowers, thali elements, and fabric for gift photos instead of screens.",
            "Avoid copied messages when writing for a close sibling.",
            "A simple thank you can make the card unforgettable.",
            "Let the jewellery match the personality of the recipient.",
            "The best rakhi card sounds like your real sibling bond.",
        ]),
    ]
    write_article(
        rank=14,
        prefix=r14_prefix,
        title="Rakhi Greeting Card 2026",
        slug=r14_slug,
        meta_desc="Rakhi greeting card 2026 messages, wishes, quotes, and warm lines for brother, sister, bhaiya bhabhi, kids, family, handmade cards, and keepsakes today.",
        focus_kw=r14_kw,
        intro=[
            "A rakhi greeting card should feel personal, warm, and full of sibling love. Use these 2026 Rakhi card messages for brothers, sisters, funny notes, heartfelt wishes, quotes, handmade cards, and gift tags.",
            "TL;DR: Write a short wish for a simple card, a funny line for a teasing sibling, an emotional note for long-distance Rakhi, and one memory when the card comes with a gift.",
        ],
        sections=rakhi_sections,
        faqs=common_faqs("Rakhi greeting card", "rakhi greeting card messages"),
        config={
            "carousel_id": "bs-cf-rakhigreetingcard",
            "occasion_year": "Rakhi 2026",
            "carousel_alt_prefix": "rakhi greeting card 2026 gift idea",
            "gift_h2": "Rakhi Gift Ideas to Pair with Greeting Cards",
            "gift_blurb": "A rakhi card becomes more meaningful when the gift feels chosen for the bond. These BlueStone picks work for siblings who love subtle, festive, or symbolic jewellery.",
            "conclusion_html": "A rakhi greeting card is most meaningful when it sounds like your real sibling bond. Keep it sincere, add one shared memory, and let the wish feel personal.",
            "schema_keywords": r14_keywords,
            "products": r14_products,
            "flatlay_insert_h2": "Rakhi Greeting Card for Brother",
            "lifestyle_insert_h2": "Rakhi Gift Message Ideas",
            "more_reads_html": 'Read more Rakhi ideas in <a href="https://blog.bluestone.com/rakhi-wishes-for-brother-2026/">Rakhi wishes for brother</a>, <a href="https://blog.bluestone.com/rakhi-gifts-for-brother-2026/">Rakhi gifts for brother</a>, and <a href="https://blog.bluestone.com/rakhi-gift-for-sister-2026/">Rakhi gifts for sister</a>.',
            "how_to_html": "Start with the relationship, add one memory or blessing, then close with a warm Rakhi wish. Keep funny lines for siblings who enjoy teasing and emotional notes for keepsake cards.",
            "faq_h2": "Frequently Asked Questions about Rakhi Greeting Cards",
            "min_lines": 84,
        },
        optimize=False,
        manifest=r14_manifest,
    )

    # Rank 15
    r15_prefix = "Week34_Rank15_NationalBestFriendsDay"
    r15_slug = "national-best-friends-day-wishes-2026"
    r15_kw = "national best friends day wishes"
    r15_keywords = [r15_kw, "national best friends day messages", "best friend wishes", "best friend captions", "friendship quotes"]
    r15_products = [
        product(product_rows, "The Pervinca Charm Holder Bracelet"),
        product(product_rows, "The Anya Ring"),
        product(product_rows, "The Aleena Huggie Earrings"),
        product(product_rows, "The Tapia Chain Bracelet"),
        product(product_rows, "The Shining Star Bracelet"),
        product(product_rows, "The Quinn Ring"),
    ]
    r15_hero = consolidated(detail_rows, "The Pervinca Charm Holder Bracelet")
    r15_flat = consolidated(detail_rows, "The Anya Ring")
    r15_life = consolidated(detail_rows, "The Aleena Huggie Earrings")
    r15_manifest = manifest_base(15, r15_slug, r15_kw, r15_prefix, "National Best Friends Day", "gift-wrap-station", r15_keywords)
    r15_manifest["slots"] = {
        "hero": manifest_slot(
            item=r15_hero,
            alt="national best friends day wishes 2026 hero with The Pervinca Charm Holder Bracelet",
            caption="National Best Friends Day 2026 mood: The Pervinca Charm Holder Bracelet",
            refs=[raw_image("Bracelets", "The Pervinca Charm Holder Bracelet", "1_body_portrait.png"), raw_image("Bracelets", "The Pervinca Charm Holder Bracelet", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="National Best Friends Day wishes 2026 hero",
                scene="solo fair-skinned Indian adult woman in a cream linen top wrapping a small gift box with ribbon beside flowers and ceramic cups, full face visible, wrist and bracelet clearly visible, relaxed warm home mood",
                product_name="The Pervinca Charm Holder Bracelet",
                product=r15_hero,
                body_part="wrist",
                extra_negatives="watch, extra bracelet, friendship band, blank card, phone",
            ),
        ),
        "flatlay": manifest_slot(
            item=r15_flat,
            alt="national best friends day wishes 2026 flatlay with The Anya Ring",
            caption="National Best Friends Day 2026 detail: The Anya Ring",
            refs=[raw_image("Rings", "The Anya Ring", "0_primary.png"), raw_image("Rings", "The Anya Ring", "2_front.png"), raw_image("Rings", "The Anya Ring", "6_angle.png")],
            roles=["primary", "front", "angle"],
            prompt=prompt_flatlay(
                occasion="National Best Friends Day wishes 2026",
                setting="gift-wrap-station",
                setting_prompt="warm cream gift wrapping table with silk ribbon, dried flowers, small wrapped box, ceramic cup, closed blank book blurred at edge, no card and no text",
                product_name="The Anya Ring",
                product=r15_flat,
            ),
        ),
        "lifestyle": manifest_slot(
            item=r15_life,
            alt="national best friends day wishes 2026 lifestyle with The Aleena Huggie Earrings",
            caption="National Best Friends Day 2026 look: The Aleena Huggie Earrings",
            refs=[raw_image("Earrings", "The Aleena Huggie Earrings", "1_body_portrait.png"), raw_image("Earrings", "The Aleena Huggie Earrings", "0_primary.png")],
            roles=["body_image", "front_primary"],
            prompt=prompt_people(
                occasion="National Best Friends Day wishes 2026 lifestyle",
                scene="solo fair-skinned Indian adult woman smiling while arranging flowers next to two ceramic cups and a wrapped gift, no device and no card facing camera, full head visible and both ears visible, ivory blouse, no necklace and wrists out of frame",
                product_name="The Aleena Huggie Earrings",
                product=r15_life,
                body_part="ear",
                extra_negatives="necklace, bracelet, ring, watch, phone, laptop, blank rectangle",
            ),
        ),
    }
    best_sections = [
        sec("National Best Friends Day Wishes", [
            "Happy National Best Friends Day to the person who makes life easier, funnier, and warmer.",
            "Wishing my best friend a day filled with love, laughter, and all the happiness you give others.",
            "You are the friend who makes ordinary days feel like something worth remembering.",
            "Happy National Best Friends Day. Thank you for being my constant support.",
            "Some friends become family, and you are one of the rare ones.",
            "May our friendship keep growing with trust, humour, and endless stories.",
            "Today is for celebrating the person who has made my life brighter.",
            "Happy Best Friends Day to my favourite listener and loudest cheerleader.",
            "You have made so many difficult days softer just by being there.",
            "Wishing you the joy, kindness, and care you always give me.",
            "Our friendship is one of the best parts of my life.",
            "Happy National Best Friends Day, bestie. Stay exactly this wonderful.",
        ]),
        sec("Short Best Friends Day Messages", [
            "Happy Best Friends Day, bestie.",
            "Grateful for you always.",
            "You are my forever person.",
            "Best friend, best blessing.",
            "Thanks for being my constant.",
            "Life is brighter with you.",
            "Cheers to our friendship.",
            "You make everything better.",
            "My favourite human, always.",
            "Real friends are rare.",
            "Our bond means everything.",
            "Happy day to us.",
        ]),
        sec("Funny National Best Friends Day Wishes", [
            "Happy Best Friends Day to the person who knows too much and still keeps my secrets.",
            "Thanks for being my best friend and unpaid life consultant.",
            "You are my favourite bad idea with excellent intentions.",
            "Our friendship is powered by snacks, gossip, and questionable advice.",
            "Happy Best Friends Day. I would share fries with you, probably.",
            "You understand my drama before I finish explaining it.",
            "Thanks for supporting my decisions and judging them later.",
            "We are proof that two chaotic people can create a stable friendship.",
            "Best friends do not let best friends overthink alone.",
            "You are weird, loyal, and therefore perfect.",
            "Happy Best Friends Day to my emergency laughter button.",
            "Our friendship deserves its own warning label.",
        ]),
        sec("Emotional Best Friend Wishes", [
            "Thank you for loving me through changes, silences, and imperfect days.",
            "You have been a safe place in a world that often feels too loud.",
            "Happy Best Friends Day to the person who understands my heart without many words.",
            "I hope you know how deeply your friendship has shaped my life.",
            "Some bonds are not loud, but they are steady and life giving.",
            "Your presence has made many hard moments easier to carry.",
            "I am grateful for every honest conversation and every shared laugh.",
            "A true best friend is a blessing that grows more precious with time.",
            "Happy National Best Friends Day. You are one of my life’s quiet miracles.",
            "Thank you for staying close in the ways that matter.",
            "Your friendship has been comfort, courage, and joy together.",
            "May life give you the same kindness you have always given me.",
        ]),
        sec("National Best Friends Day Captions", [
            "Best friend energy forever.",
            "Found my person and kept them.",
            "Friendship that feels like home.",
            "The real one, the rare one.",
            "Laughter, loyalty, and lifelong stories.",
            "Celebrating my favourite constant.",
            "National Best Friends Day with my forever human.",
            "Good friends glow differently.",
            "A bond worth every memory.",
            "Bestie by choice, family by heart.",
            "Grateful for this beautiful chaos.",
            "Our friendship deserves the spotlight.",
        ]),
        sec("Best Friend Gift Note Ideas", [
            "Write a note that mentions one memory only the two of you understand.",
            "Choose a bracelet when you want the gift to feel like a daily reminder.",
            "A ring can mark a shared promise or a milestone friendship.",
            "Earrings work beautifully for a friend who enjoys subtle sparkle.",
            "Keep the message honest instead of overly dramatic.",
            "Say thank you for a specific moment when they stood by you.",
            "A small keepsake can make a simple wish feel permanent.",
            "Use flowers, ribbons, and warm wrapping for gift photos, not screens.",
            "Avoid generic bestie lines if your bond has its own language.",
            "Mention why this friendship feels rare.",
            "Let the gift and the note feel calm, thoughtful, and chosen.",
            "The best gift note sounds like a private smile.",
        ]),
        sec("National Best Friends Day Quotes", [
            "A best friend is the person who makes your real self feel safe.",
            "The rarest friendship is the one that gives you room to grow.",
            "Good friends make memories. Best friends become part of them.",
            "A true friend is both mirror and shelter.",
            "Some friendships are proof that kindness has a voice.",
            "Best friends turn ordinary days into comfort stories.",
            "The strongest bonds are built through trust, not perfection.",
            "A best friend is a home you can call from anywhere.",
            "Real friendship is steady love in everyday form.",
            "Some people arrive as friends and stay as blessings.",
            "Best friends are the family our hearts recognise.",
            "A beautiful friendship is one that keeps choosing care.",
        ]),
    ]
    write_article(
        rank=15,
        prefix=r15_prefix,
        title="National Best Friends Day Wishes 2026",
        slug=r15_slug,
        meta_desc="National Best Friends Day wishes 2026 with short messages, captions, quotes, funny lines, emotional notes, and greetings for your closest friends today.",
        focus_kw=r15_kw,
        intro=[
            "National best friends day wishes should feel close, honest, and easy to send. This 2026 collection includes short messages, funny wishes, emotional notes, captions, quotes, and gift note ideas for the friend who feels like chosen family.",
            "TL;DR: Use a short wish for chats, a funny line for your bestie, an emotional note for someone who stood by you, and a gift message when you want the moment to feel lasting.",
        ],
        sections=best_sections,
        faqs=common_faqs("National Best Friends Day", "national best friends day wishes"),
        config={
            "carousel_id": "bs-cf-nationalbestfriends",
            "occasion_year": "National Best Friends Day 2026",
            "carousel_alt_prefix": "national best friends day wishes 2026 gift idea",
            "gift_h2": "Best Friend Gift Ideas with Wishes",
            "gift_blurb": "A best friend wish becomes more memorable when it comes with a small keepsake. These BlueStone pieces are easy to pair with a note that feels personal and warm.",
            "conclusion_html": "National best friends day wishes work best when they sound like your friendship. Choose a line that fits your best friend, then add one detail only they would understand.",
            "schema_keywords": r15_keywords,
            "products": r15_products,
            "flatlay_insert_h2": "Funny National Best Friends Day Wishes",
            "lifestyle_insert_h2": "Best Friend Gift Note Ideas",
            "more_reads_html": 'Read more friendship ideas in <a href="https://blog.bluestone.com/happy-friendship-day-quotes-2026/">Happy Friendship Day quotes</a>, <a href="https://blog.bluestone.com/international-friendship-day-quotes-2026/">international friendship day quotes</a>, and <a href="https://blog.bluestone.com/friendship-day-gifts-2026/">friendship day gifts</a>.',
            "how_to_html": "Choose the tone first. Funny lines suit playful best friends, emotional notes suit deep bonds, and captions work best when they are short enough to pair with a photo.",
            "faq_h2": "Frequently Asked Questions about National Best Friends Day Wishes",
            "min_lines": 84,
        },
        optimize=True,
        manifest=r15_manifest,
    )


if __name__ == "__main__":
    build()
